spring:
  application:
    name: accounts-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.event.merge.entity_copy_observer: allow
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/accounts-service-db
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
info:
  app:
    name: accounts-service
    description: microservicio de administracion de billetera virtual
    version: 1.0.0

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: http://localhost:8082/actuator/info
    healthCheckUrlPath: http://localhost:8082/actuator/health

server:
  port: 8082
