spring:
  application:
    name: cards-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.event.merge.entity_copy_observer: allow
  datasource:
    url: jdbc:mysql://mysql:3306/dmhdatabase?createDatabaseIfNotExist=true&serverTimezone=UTC
    #url: jdbc:mysql://127.0.0.1:3306/cards-service-db
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
info:
  app:
    name: cards-service
    description: microservicio de administracion y registro de tarjetas de credito y debito
    version: 1.0.0

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: http://localhost:8084/actuator/info
    healthCheckUrlPath: http://localhost:8084/actuator/health
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8085
