spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        serviceId: config-server
        enabled: true
    gateway:
      global-cors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:5173"
            #allowedHeaders: '*'
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowed-headers:
              - Origin
              - X-Requested-With
              - Content-Type
              - Accept
              - Authorization
            allow-credentials: true
            max-age: 3600
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/user/**        
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/account/**


management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
info:
  app:
    name: Gateway
    description: API gateway (remote)
    version: 1.0.0

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: http://localhost:8084/actuator/info
    healthCheckUrlPath: http://localhost:8084/actuator/info


server:
  port: 8084
