spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        serviceId: config-server
        enabled: true
    gateway:
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/user/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - PATCH
              allowedHeaders: '*'
              maxAge: 30
          
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/account/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - PATCH
              allowedHeaders: '*'
              maxAge: 30


management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
info:
  app:
    name: Gateway
    description: API gateway
    version: 1.0.0

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: http://localhost:8084/actuator/info
    healthCheckUrlPath: http://localhost:8084/actuator/info


server:
  port: 8084
