spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        serviceId: config-server
        enabled: true
    gateway:
      default-filters:
        - AddRequestHeader=X-Request-generated-by, gateway-service
        - AddResponseHeader=X-Response-generated-by, gateway-service
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            #allowedOrigins: "http://localhost:5173"
            #allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Origin
              - X-Requested-With
              - Content-Type
              - Accept
              - Authorization
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/user/**
            
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/account/**


management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
info:
  app:
    name: Gateway
    description: API gateway (remote)
    version: 1.0.0

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: http://localhost:8084/actuator/info
    healthCheckUrlPath: http://localhost:8084/actuator/info


server:
  port: 8084
