spring:
  application:
    name: users-service
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.event.merge.entity_copy_observer: allow
    datasource:
      #url: jdbc:mysql://127.0.0.1:3307/users_service
      url: jdbc:mysql://127.0.0.1:3306/user-service-db
      username: root
      password: admin
      driverClassName: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${dh.keycloak.clientId}
            client-secret: ${dh.keycloak.clientSecret}
            scope: openid
            realm: ${dh.keycloak.realm}
            serverUrl: ${dh.keycloak.serverUrl}
        provider:
          keycloak:
            issuer-uri: ${dh.keycloak.serverUrl}/realms/${dh.keycloak.realm}
        resourceserver:
          jwt:
            issuer-uri: ${dh.keycloak.serverUrl}/realms/${dh.keycloak.realm}
            jwk-set-uri: ${dh.keycloak.serverUrl}/realms/${dh.keycloak.realm}/protocol/openid-connect/certs

dh:
  keycloak:
    realm: dh-money-users
    serverUrl: http://localhost:8080
    clientId: api-dh-money
    clientSecret: 2bgKXNvbhtpbEUux2QmNfUev6D5hzqA4
    tokenEndpoint: ${dh.keycloak.serverUrl}/realms/${dh.keycloak.realm}/protocol/openid-connect/token
    
#Notebook: 9jvDMRt9K1cujgirQ5WUizCKIJ5pqA4V
#PC: 2bgKXNvbhtpbEUux2QmNfUev6D5hzqA4

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
info:
  app:
    name: users-service
    description: microservicio de registro y logueo (desde config server)
    version: 1.0.0

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: http://localhost:8081/actuator/info
    healthCheckUrlPath: http://localhost:8081/actuator/health
  #client:
    #serviceUrl:
      #defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8081
    

# MySQL Database Configuration
# spring.jpa.hibernate.ddl-auto=create-drop
# spring.datasource.url=jdbc:mysql://127.0.0.1:3306/user-service-db
# spring.datasource.username=root
# spring.datasource.password=admin
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.show-sql= true
# spring.jpa.properties.hibernate.event.merge.entity_copy_observer=allow

#Actuator
# management.endpoints.web.exposure.include=health,info
# management.info.env.enabled=true
# info.app.name=users-service
# info.app.description=microservicio de registro y logueo (desde config server)
# info.app.version=1.0.0

#Redireccionamiento de URL
# eureka.instance.statusPageUrlPath=http://localhost:8081/actuator/info
# eureka.instance.healthCheckUrlPath=http://localhost:8081/actuator/health



